services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
      - postgres
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: open_admin_test
      DB_USERNAME: root
      DB_PASSWORD: root
    tty: true

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: open_admin_test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: open_admin_test
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  db_data:
  pg_data: