
name: Pest Tests (SQLite)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pest-tests:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_sqlite
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare environment
        run: cp .env.test.sqlite .env

      - name: Generate Application Key
        run: php artisan key:generate || true

      - name: Run Pest Tests with Coverage
        run: ./vendor/bin/pest --coverage-html=coverage-report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
